services:
  backend:
    build: ./backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:h2:mem:reporting;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH
      SPRING_DATASOURCE_USERNAME: sa
      SPRING_DATASOURCE_PASSWORD: ""

  frontend:
    build: ./frontend
    depends_on:
      - backend
    ports:
      - "3000:80"
